version: "3.8"

services:
  web:
    build:
      context: "."
      platforms:
        - linux/arm64/v8
    image: ghcr.io/tuky191/sre-challenge-michal:v0.0.1
    container_name: web-service
    stop_signal: SIGINT
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=true
      - FLASK_RUN_HOST=0.0.0.0
