version: "3.8"

services:
  web:
    build:
      context: "."
      platforms:
        - linux/arm64/v8
    image: ghcr.io/tuky191/sre-challenge-michal:v0.0.1
    container_name: service
    stop_signal: SIGINT
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=true
      - FLASK_RUN_HOST=0.0.0.0
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "redis:6.2-alpine"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
