[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.web]
    address = ":80"

[api]
  dashboard = true

[providers]
  docker = true

[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"
    addEntryPointsLabels = true
    addServicesLabels = true
